In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.17660191, 0.6411013 , 0.55076054, 0.72755812, 0.44911322])

In [22]:
np.random.rand(5,5)

array([[0.62992333, 0.63328236, 0.41827823, 0.10684982, 0.53425507],
       [0.53002167, 0.75862994, 0.36244859, 0.00268471, 0.51713149],
       [0.94702481, 0.48582607, 0.66815657, 0.39368274, 0.9683154 ],
       [0.04512188, 0.75031559, 0.77801202, 0.38721304, 0.27273345],
       [0.81685122, 0.02404728, 0.15363813, 0.10040742, 0.30674652]])

In [23]:
np.random.rand(4,4)

array([[0.57490963, 0.61723156, 0.45460923, 0.29157452],
       [0.30569833, 0.26050662, 0.37152835, 0.91150594],
       [0.39060451, 0.54339355, 0.55575052, 0.48975378],
       [0.00991403, 0.67113925, 0.9931023 , 0.39992073]])

In [24]:
np.random.randint(1,100,10)

array([19, 92, 41, 63,  3,  1,  1, 27, 74,  1])

In [27]:
 arr=np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([43,  2, 37, 49, 49, 47,  8, 40,  2,  5])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

49

In [36]:
ranarr.min()

2

In [37]:
ranarr.argmax()

3

In [38]:
ranarr.argmin()

1

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [44]:
arr.shape

(5, 5)

In [48]:
arr.dtype

dtype('int32')

In [49]:
### NumPy Indexing and Selection

In [50]:
import numpy as np

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [59]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[0:5] = 100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
 arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [66]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
arr_2d[0][2]

15

In [73]:
arr_2d[2,2]

45

In [74]:
arr_2d[:1,0:]

array([[ 5, 10, 15]])

In [75]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
bool_arr=arr < 15

In [80]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [81]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [1]:
## NumPy Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [11]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [12]:
arr / arr

C:\Users\abdulrasaq.bilau\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
 1/arr

C:\Users\abdulrasaq.bilau\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.log(arr)

C:\Users\abdulrasaq.bilau\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])